# Generated by Django 3.2.7 on 2021-10-04 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cctv',
            fields=[
                ('cctvId', models.AutoField(db_column='cctvId', primary_key=True, serialize=False)),
                ('latitude', models.FloatField(db_column='latitude')),
                ('longtitude', models.FloatField(db_column='longtitude')),
                ('address', models.TextField(db_column='address')),
                ('detect', models.IntegerField(db_column='detect', default=0)),
            ],
            options={
                'db_table': 'cctv',
            },
        ),
        migrations.CreateModel(
            name='Violent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violentTime', models.DateTimeField(auto_now_add=True, db_column='violentTime')),
                ('violentRate', models.IntegerField(db_column='violentRate', default=0)),
                ('cctvId', models.ForeignKey(db_column='cctvId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.cctv')),
            ],
            options={
                'db_table': 'violent',
            },
        ),
    ]
