# Generated by Django 3.1.3 on 2021-10-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20211011_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
